### ISSUE TITLE
Bug: LUA errors when doing dungeon Mists of Tirna Scithe

### ISSUE THREAD

**Issue by zohrath** [ImogenBits/tidyplates#40] opened 2021-01-10 14:28 UTC
Well, at least when doing Mists, I get this:

Message: Interface\AddOns\TidyPlates\TidyPlatesCore.lua:687: attempt to index local 'iconCoord' (a nil value)
Time: Sun Jan 10 15:19:46 2021
Count: 1006
Stack: Interface\AddOns\TidyPlates\TidyPlatesCore.lua:687: attempt to index local 'iconCoord' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:687: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:683>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:721: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:717>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:306: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:293>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:422: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:412>
[string "@Interface\AddOns\TidyPlates\TidyPlatesCore.lua"]:142: in function <Interface\AddOns\TidyPlates\TidyPlatesCore.lua:121>

Locals:

**Comment by ImogenBits** [comment] 2021-01-10 14:29
Duplicate of #37

**Closed by ImogenBits** 2021-01-10 14:29 UTC
