### ISSUE TITLE
Combo Points bugging out

### ISSUE THREAD

**Issue by luckysock** [ImogenBits/tidyplates#50] opened 2021-03-09 15:55 UTC
On classes that don't even use combo points, i am getting combo points that go from 0 to full and disappear every time I enter combat. This started around the beginning of March on my Survival Hunter using the default DPS profile.

**Comment by ImogenBits** [comment] 2021-03-09 16:00
Duplicate of #32

**Closed by ImogenBits** 2021-03-09 16:00 UTC
