### ISSUE TITLE
Personal resource display broken in PVP

### ISSUE THREAD

**Issue by Dayvii** [ImogenBits/tidyplates#34] opened 2020-12-28 01:54 UTC
I saw you fixed personal resource display being broken and I applied that code manually myself. It worked fine for PvE.
However, it does not work in PVP. There are still situations where my health bar and buffs vanish. The bottom half of the bar (mana and holy power) is still there.

**Comment by ImogenBits** [comment] 2020-12-30 08:30
Duplicate of #23

**Closed by ImogenBits** 2020-12-30 08:30 UTC
