### ISSUE TITLE
Show Personal Resources Bug

### ISSUE THREAD

**Issue by pandalffx** [ImogenBits/tidyplates#39] opened 2021-01-09 04:02 UTC
Often when I am using tidyplates, the healthbar and buffs icons on my personal resource display are no longer visible. i can only see my mana bar. its as if the bars between the health and mana are split and pushes the health and buff icons "upwards" where they are no longer visible. very weird. i have seen similar posts regarding this but no fix has been mentioned.

**Comment by MrMontte** [comment] 2021-01-10 02:46
I'm getting this bug as well, and it happens randomly. Hoping to bump this post to get it addressed.

**Comment by ImogenBits** [comment] 2021-01-10 14:31
Duplicate of #23

**Closed by ImogenBits** 2021-01-10 14:31 UTC
