### ISSUE TITLE
Most Recent Update Causing LUA Errors

### ISSUE THREAD

**Issue by OldWorldRaiders** [ImogenBits/tidyplates#58] opened 2021-07-02 16:19 UTC
11x [ADDON_ACTION_BLOCKED] AddOn 'TidyPlatesWidgets' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:311: in function `SetClassNameplateBar'
[string "@Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua"]:92: in function `HideNameplateBar'
[string "@TidyPlatesWidgets\ComboPointWidget.lua"]:89: in function `createFunction'
[string "@TidyPlatesHub\functions\Widgets.lua"]:240: in function <TidyPlatesHub\functions\Widgets.lua:232>
[string "@TidyPlatesHub\functions\Widgets.lua"]:267: in function `OnInitializeWidgets'
[string "@TidyPlatesHub\functions\Core.lua"]:248: in function `OnInitialize'
[string "@TidyPlates\TidyPlatesCore.lua"]:381: in function <TidyPlates\TidyPlatesCore.lua:341>
[string "@TidyPlates\TidyPlatesCore.lua"]:988: in function `?'
[string "@TidyPlates\TidyPlatesCore.lua"]:954: in function <TidyPlates\TidyPlatesCore.lua:953>

**Comment by ImogenBits** [comment] 2021-07-03 11:55
can you provide a description of when this happens? I can't help you without being able to reproduce the issue.

**Comment by RootL0cus** [comment] 2021-07-20 15:52
I am getting a similar lua error that doesn't happen all the time, but once it starts it happens every few seconds.  It definitely started both times after I reloaded my ui due to another error, but that's all I have.  I'll try to add more details when it pops up again.

**Comment by OldWorldRaiders** [comment] 2021-07-23 14:52
I zoned into Ulduar, walked to Yogg Saron, and instantly got this:

15x [ADDON_ACTION_BLOCKED] AddOn 'TidyPlatesWidgets' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:311: in function `SetClassNameplateBar'
[string "@Blizzard_NamePlates\Blizzard_ClassNameplateBar.lua"]:92: in function `HideNameplateBar'
[string "@TidyPlatesWidgets\ComboPointWidget.lua"]:89: in function `createFunction'
[string "@TidyPlatesHub\functions\Widgets.lua"]:240: in function <TidyPlatesHub\functions\Widgets.lua:232>
[string "@TidyPlatesHub\functions\Widgets.lua"]:267: in function `OnInitializeWidgets'
[string "@TidyPlatesHub\functions\Core.lua"]:248: in function `OnInitialize'
[string "@TidyPlates\TidyPlatesCore.lua"]:381: in function <TidyPlates\TidyPlatesCore.lua:341>
[string "@TidyPlates\TidyPlatesCore.lua"]:988: in function `?'
[string "@TidyPlates\TidyPlatesCore.lua"]:954: in function <TidyPlates\TidyPlatesCore.lua:953>

**Comment by ImogenBits** [comment] 2021-08-09 10:10
should be fixed in the next update

**Closed by ImogenBits** 2021-08-09 10:10 UTC
Labels: bug, unable to reproduce
