### ISSUE TITLE
[LUA ERROR] If run together with elvUI and S&L

### ISSUE THREAD

**Issue by chwba** [ImogenBits/tidyplates#42] opened 2021-02-11 17:38 UTC
```
Message: Interface\AddOns\ElvUI_SLE\core\toolkit.lua:325: script ran too long
Time: Thu Feb 11 18:25:50 2021
Count: 1
Stack: Interface\AddOns\ElvUI_SLE\core\toolkit.lua:325: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_SLE\core\toolkit.lua"]:325: in function `InitializeModules'
[string "@Interface\AddOns\ElvUI_SLE\core\core.lua"]:93: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua"]:303: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:299>
[string "=[C]"]: in function `Initialize'
[string "@Interface\AddOns\ElvUI\init.lua"]:156: in function <Interface\AddOns\ElvUI\init.lua:155>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: 
Message: Interface\AddOns\ElvUI\init.lua:157: script ran too long
Time: Thu Feb 11 18:25:50 2021
Count: 1
Stack: Interface\AddOns\ElvUI\init.lua:157: script ran too long
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI\init.lua"]:157: in function <Interface\AddOns\ElvUI\init.lua:155>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
Message: ...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
Time: Thu Feb 11 18:25:50 2021
Count: 1
Stack: ...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: 
```

**Comment by ImogenBits** [comment] 2021-02-26 17:26
Duplicate of #20

**Closed by ImogenBits** 2021-02-26 17:26 UTC
Labels: bug

**Comment by chwba** [comment] 2021-03-02 16:19
For me its not causing a delay though, Shadow & Light compeltely disappears from the elvUI options menu along with all its features and bars once I activate tidyplates.

**Comment by ImogenBits** [comment] 2021-03-02 23:09
I don't use elvui at all so I can't give you a super detailed description, but from what I can tell from your error message what is happening is that TidyPlates is causing the loading screen delay, but instead of just taking a long time wow interrupts the loading process, which then causes the issue with elvui not loading correctly because it was interrupted.

**Comment by chwba** [comment] 2021-03-13 16:59
How do you suggest to proceed to solve this? elvUI + Shadow & Light + Tidy Plates sill cause S&L to disappear..

**Comment by ImogenBits** [comment] 2021-03-13 17:01
honestly the best solution I have for you right now is to not use both addons together.
it's a very weird bug that exists because of some obscure behaviour of the blizz api. I haven't found a way to actually fix it and I don't really see a fix in the near future.
If you find a way to fix it, I'd be happy to merge, but I can't really justify devoting more of my energy to this at the moment.

**Comment by chwba** [comment] 2021-03-13 17:02
I will ask over at tukui/elvui, if they can take a look at it - Its sad because S&L is a very frequently used mod for elvui

**Comment by ImogenBits** [comment] 2021-03-13 18:14
I've talked to them about it, but it sadly is just an issue with TidyPlates/blizz api that none of us were able to figure out
