### ISSUE TITLE
Undetermined dots under frames

### ISSUE THREAD

**Issue by FrenzySmile** [ImogenBits/tidyplates#49] opened 2021-03-08 07:00 UTC
Hello!
Undetermined dots began to appear above the frames of hostile characters.
Please help!
![TidyPlates bug](https://user-images.githubusercontent.com/80243324/110285835-0c592b80-800e-11eb-82d2-981b2f275136.jpg)
My addons used with Tidyplates:
1) NameplateCooldowns
2) OmniCC
3) OmniBar
4) BigDebuffs
5) BattleGroundEnemies
6) Weak auras

Best regards

**Comment by Caraman24** [comment] 2021-03-08 22:47
disable tug o threat indicator

**Comment by ImogenBits** [comment] 2021-03-08 22:49
Duplicate of #32

**Closed by ImogenBits** 2021-03-08 22:49 UTC
Labels: bug, duplicate
