### ISSUE TITLE
False False False

### ISSUE THREAD

**Issue by kh3ldar** [ImogenBits/tidyplates#47] opened 2021-02-28 02:59 UTC
Hello, I'm getting my chatbox spammed when a theme of tidyplates enabled. This only occurs on one character couldn't reproduce it on my main.

![WoWScrnShot_022821_055432](https://user-images.githubusercontent.com/79776615/109406430-0fa74400-798a-11eb-84b7-341bec818f98.jpg)

**Comment by ImogenBits** [comment] 2021-02-28 07:56
duplicate of #46On Feb 28, 2021 03:59, kh3ldar <notifications@github.com> wrote:
Hello, I'm getting my chatbox spammed when a theme of tidyplates enabled. This only occurs on one character couldn't reproduce it on my main.

**Closed** 2021-02-28 08:24 UTC
